import type { VehiclePricing } from "./types";

export const vehiclePricing: VehiclePricing[] = [
  {
    vehicleCode: "g90",
    vehicleName: "Genesis G90",
    vehicleTypeCode: "EXECUTIVE_SEDAN",
    vehicleTypeName: "Executive Sedan",
    representativeVehicle: "Genesis G90",
    category: "Executive sedan",
    maxPax: 3,
    maxLuggage: 3,
    imageUrl: "/Images/g90.webp",
    hourlyRateUsd: 65,
    seoulPtpHours: 2,
    icnFlatUsd: 180,
    gmpFlatUsd: 120,
    charter5hUsd: 330,
    charter10hUsd: 580,
    charter12hUsd: 680,
    currency: "USD",
    isActive: true,
    sortOrder: 10
  },
  {
    vehicleCode: "sclass",
    vehicleName: "Mercedes-Benz S-Class",
    vehicleTypeCode: "LUXURY_SEDAN",
    vehicleTypeName: "Luxury Sedan",
    representativeVehicle: "Mercedes-Benz S-Class",
    category: "Luxury sedan",
    maxPax: 3,
    maxLuggage: 3,
    imageUrl: "/Images/sclass.webp",
    hourlyRateUsd: 85,
    seoulPtpHours: 2,
    icnFlatUsd: 230,
    gmpFlatUsd: 160,
    charter5hUsd: 430,
    charter10hUsd: 760,
    charter12hUsd: 880,
    currency: "USD",
    isActive: true,
    sortOrder: 20
  },
  {
    vehicleCode: "escalade",
    vehicleName: "Cadillac Escalade",
    vehicleTypeCode: "SUV",
    vehicleTypeName: "SUV",
    representativeVehicle: "Cadillac Escalade",
    category: "Luxury SUV",
    maxPax: 5,
    maxLuggage: 5,
    imageUrl: "/Images/escalade.webp",
    hourlyRateUsd: 90,
    seoulPtpHours: 2.2,
    icnFlatUsd: 260,
    gmpFlatUsd: 180,
    charter5hUsd: 470,
    charter10hUsd: 820,
    charter12hUsd: 960,
    currency: "USD",
    isActive: true,
    sortOrder: 30
  },
  {
    vehicleCode: "staria",
    vehicleName: "Hyundai Staria",
    vehicleTypeCode: "MPV",
    vehicleTypeName: "MPV",
    representativeVehicle: "Hyundai Staria",
    category: "Premium van",
    maxPax: 6,
    maxLuggage: 7,
    imageUrl: "/Images/staria.webp",
    hourlyRateUsd: 70,
    seoulPtpHours: 2,
    icnFlatUsd: 210,
    gmpFlatUsd: 145,
    charter5hUsd: 360,
    charter10hUsd: 630,
    charter12hUsd: 740,
    currency: "USD",
    isActive: true,
    sortOrder: 40
  },
  {
    vehicleCode: "sprinter",
    vehicleName: "Mercedes-Benz Sprinter",
    vehicleTypeCode: "SPRINTER",
    vehicleTypeName: "Sprinter",
    representativeVehicle: "Mercedes-Benz Sprinter",
    category: "Executive van",
    maxPax: 13,
    maxLuggage: 12,
    imageUrl: "/Images/sprinter519.webp",
    hourlyRateUsd: 115,
    seoulPtpHours: 2.5,
    icnFlatUsd: 360,
    gmpFlatUsd: 270,
    charter5hUsd: 620,
    charter10hUsd: 1050,
    charter12hUsd: 1220,
    currency: "USD",
    isActive: true,
    sortOrder: 50
  }
];

export function getVehiclePricing(vehicleCode: string) {
  return vehiclePricing.find((vehicle) => vehicle.vehicleCode === vehicleCode && vehicle.isActive);
}
