import type { VehiclePricing } from "./types";

export const vehiclePricing: VehiclePricing[] = [
  {
    vehicleCode: "staria",
    vehicleName: "Hyundai Staria",
    vehicleTypeCode: "MPV",
    vehicleTypeName: "MPV",
    representativeVehicle: "Hyundai Staria",
    category: "Premium van",
    maxPax: 5,
    maxLuggage: 5,
    imageUrl: "/Images/staria.webp",
    hourlyRateUsd: 50,
    seoulPtpHours: 2,
    icnFlatUsd: 150,
    gmpFlatUsd: 135,
    charter5hUsd: 250,
    charter10hUsd: 400,
    charter12hUsd: 500,
    currency: "USD",
    isActive: true,
    sortOrder: 10
  },
  {
    vehicleCode: "carnival",
    vehicleName: "Kia Carnival",
    vehicleTypeCode: "MPV",
    vehicleTypeName: "MPV",
    representativeVehicle: "Kia Carnival",
    category: "Premium MPV",
    maxPax: 5,
    maxLuggage: 5,
    imageUrl: "/Images/carnival.webp",
    hourlyRateUsd: 50,
    seoulPtpHours: 2,
    icnFlatUsd: 150,
    gmpFlatUsd: 135,
    charter5hUsd: 250,
    charter10hUsd: 400,
    charter12hUsd: 500,
    currency: "USD",
    isActive: true,
    sortOrder: 20
  },
  {
    vehicleCode: "g90",
    vehicleName: "Genesis G90",
    vehicleTypeCode: "EXECUTIVE_SEDAN",
    vehicleTypeName: "Executive Sedan",
    representativeVehicle: "Genesis G90",
    category: "Executive sedan",
    maxPax: 3,
    maxLuggage: 3,
    imageUrl: "/Images/g90.webp",
    hourlyRateUsd: 70,
    seoulPtpHours: 2,
    icnFlatUsd: 200,
    gmpFlatUsd: 180,
    charter5hUsd: 350,
    charter10hUsd: 560,
    charter12hUsd: 700,
    currency: "USD",
    isActive: true,
    sortOrder: 30
  },
  {
    vehicleCode: "suburban",
    vehicleName: "Chevrolet Suburban",
    vehicleTypeCode: "SUV",
    vehicleTypeName: "SUV",
    representativeVehicle: "Chevrolet Suburban",
    category: "Full-size SUV",
    maxPax: 5,
    maxLuggage: 5,
    imageUrl: "/Images/suburban.webp",
    hourlyRateUsd: 70,
    seoulPtpHours: 2,
    icnFlatUsd: 200,
    gmpFlatUsd: 180,
    charter5hUsd: 350,
    charter10hUsd: 560,
    charter12hUsd: 700,
    currency: "USD",
    isActive: true,
    sortOrder: 40
  },
  {
    vehicleCode: "escalade",
    vehicleName: "Cadillac Escalade",
    vehicleTypeCode: "SUV",
    vehicleTypeName: "SUV",
    representativeVehicle: "Cadillac Escalade",
    category: "Luxury SUV",
    maxPax: 5,
    maxLuggage: 5,
    imageUrl: "/Images/escalade.webp",
    hourlyRateUsd: 100,
    seoulPtpHours: 2,
    icnFlatUsd: 300,
    gmpFlatUsd: 270,
    charter5hUsd: 500,
    charter10hUsd: 800,
    charter12hUsd: 1000,
    currency: "USD",
    isActive: true,
    sortOrder: 50
  },
  {
    vehicleCode: "s_class",
    vehicleName: "Mercedes S-Class",
    vehicleTypeCode: "LUXURY_SEDAN",
    vehicleTypeName: "Luxury Sedan",
    representativeVehicle: "Mercedes S-Class",
    category: "Luxury sedan",
    maxPax: 3,
    maxLuggage: 3,
    imageUrl: "/Images/sclass.webp",
    hourlyRateUsd: 100,
    seoulPtpHours: 2,
    icnFlatUsd: 350,
    gmpFlatUsd: 315,
    charter5hUsd: 550,
    charter10hUsd: 800,
    charter12hUsd: 1000,
    currency: "USD",
    isActive: true,
    sortOrder: 60
  },
  {
    vehicleCode: "sprinter_8",
    vehicleName: "Sprinter (8 Pax)",
    vehicleTypeCode: "SPRINTER",
    vehicleTypeName: "Sprinter",
    representativeVehicle: "Mercedes-Benz Sprinter",
    category: "Executive van",
    maxPax: 8,
    maxLuggage: 8,
    imageUrl: "/Images/sprinter319.webp",
    hourlyRateUsd: 70,
    seoulPtpHours: 2,
    icnFlatUsd: 250,
    gmpFlatUsd: 225,
    charter5hUsd: 350,
    charter10hUsd: 560,
    charter12hUsd: 700,
    currency: "USD",
    isActive: true,
    sortOrder: 70
  },
  {
    vehicleCode: "sprinter_13",
    vehicleName: "Sprinter (13 Pax)",
    vehicleTypeCode: "SPRINTER",
    vehicleTypeName: "Sprinter",
    representativeVehicle: "Mercedes-Benz Sprinter",
    category: "Executive van",
    maxPax: 13,
    maxLuggage: 10,
    imageUrl: "/Images/sprinter519.webp",
    hourlyRateUsd: 80,
    seoulPtpHours: 2,
    icnFlatUsd: 300,
    gmpFlatUsd: 270,
    charter5hUsd: 500,
    charter10hUsd: 640,
    charter12hUsd: 800,
    currency: "USD",
    isActive: true,
    sortOrder: 80
  },
  {
    vehicleCode: "sprinter_lux",
    vehicleName: "Sprinter Luxury (7 Pax)",
    vehicleTypeCode: "SPRINTER",
    vehicleTypeName: "Sprinter",
    representativeVehicle: "Mercedes-Benz Sprinter Luxury",
    category: "Luxury van",
    maxPax: 7,
    maxLuggage: 6,
    imageUrl: "/Images/sprinter519.webp",
    hourlyRateUsd: 100,
    seoulPtpHours: 2,
    icnFlatUsd: 400,
    gmpFlatUsd: 360,
    charter5hUsd: 550,
    charter10hUsd: 800,
    charter12hUsd: 1000,
    currency: "USD",
    isActive: true,
    sortOrder: 90
  }
];

export function getVehiclePricing(vehicleCode: string) {
  return vehiclePricing.find((vehicle) => vehicle.vehicleCode === vehicleCode && vehicle.isActive);
}
